name: test docker compose
on:
  push:
    branches:
      - develop # or any branch you want to trigger the publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

#      - name: Install Docker using Docker's official script
#        run: |
#          curl -fsSL https://get.docker.com -o get-docker.sh
#          sudo sh get-docker.sh
#        continue-on-error: false

#      - name: Install Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#        continue-on-error: false

#      - name: Install dependencies
#        run: npm install
#        continue-on-error: false

      - name: check files in home dir
        run: |
          ls -l
          pwd
          ls -l /home/runner/work/testcontainers-ci-cd/
          ls -l /home/runner/work/testcontainers-ci-cd/testcontainers-ci-cd/
          ls -l ${{ github.workspace }}/docker_compose/

#      - name: Start application-specific services using Docker Compose
#        run: docker-compose -f ./docker_compose/docker-compose.yml up -d
#        continue-on-error: false